---
kind: pipeline
type: docker
name: linux-amd64

platform:
  arch: amd64
  os: linux

steps:
  - name: test
    image: golang:1.18.8
    commands:
      - echo "测试代码"

  - name: build
    image: golang:1.18.8
    commands:
      - echo "构建二进制文件"
      - go build
    environment:
      GOARCH: amd64
      GOOS: linux

  - name: publish
    image: plugins/docker:18
    settings:
      auto_tag: true
      auto_tag_suffix: linux-amd64
      dockerfile: Dockerfile
      registry: registry.cn-hangzhou.aliyuncs.com
      repo: chenshiwei/example-project
      username: 16601163553
      password: bigeye7963
    when:
      event:
        - tag

trigger:
  branch:
    - master
  event:
    - cron
    - tag